# Database
MYSQL_USERNAME: root
MYSQL_PASSWORD: root
MYSQL_HOST: mysql-db-container
MYSQL_PORT: 3306
MYSQL_DATABASE: securedb

# Server
CONTAINER_PORT: 8085
ACTIVE_PROFILE: prod

# Email
EMAIL_HOST: smtp.gmail.com
EMAIL_PORT: 587
EMAIL_USERNAME:
EMAIL_PASSWORD:

# Verify
VERIFY_HOST: http://localhost:${CONTAINER_PORT}

# UI
UI_APP_URL: http://localhost:4200

JWT_SECRET: verysecretkey